# Service configuration
kind: Service
apiVersion: v1
metadata:
  name: datastore-stack
  labels:
    app: datastore
spec:
  ports:
  - port: 27017
  selector:
    app: datastore
  clusterIP: None
---
# StatefulSet configuration
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: datastore
spec:
  serviceName: datastore-stack
  replicas: 1
  selector:
    matchLabels:
      app: datastore
      selector: datastore
  template:
    metadata:
      labels:
        app: datastore
        selector: datastore
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: datastore-pv
          mountPath: /data/db
      volumes:
      - name: datastore-pv
        persistentVolumeClaim:
          claimName: datastore-pvc
