kind: Pod
apiVersion: v1
metadata:
  name: initdb
  labels: 
    name: initdb
spec:
  containers:
  - name: initdb
    image: mcaliandro/smarthome:initdb
    command: [ 'sleep', 'infinity' ]
    env:
    - name: DB_HOST
      value: "<ip-address>" # set the pod hostname
    - name: DB_PORT
      value: "27017" # set the exposed port
    - name: DB_NAME
      value: "smarthome" # set the database name
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred # credential for pulling from DockerHub
  restartPolicy: Never
