# Deployment configuration
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: core-deploy
spec:
  replicas: 3 # define the number of replicas
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core
        image: mcaliandro/smarthome:corev1 # using the private repository on DockerHub
        ports:
        - containerPort: 5000 # application default port
        env:
        - name: DB_HOST
          value: "<ip-address>" # define the pod IP address
        - name: DB_PORT
          value: "27017" # define the exposed port
        - name: DB_NAME
          value: "smarthome" # define the database name
        imagePullPolicy: Always
      imagePullSecrets:
      - name: dockerhub # credential for pulling from DockerHub
---
# Service configuration
kind: Service
apiVersion: v1
metadata:
  name: core-stack
  labels:
    app: core
spec:
  selector:
    app: core
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5000 # application default port
    targetPort: 5000 # application default port
    nodePort: 30050 # port exposed by the service
